### PR TITLE
CMake project improvements

### PR DESCRIPTION
**Pull request by forderud**
Improve the CMake project setup so that it becomes compatible with newer C++ compilers than MSVC2012. Also, make it compatible with newer Qt versions and simplify the find_package statements.

This project was the first hit I got when googling "cmake qt qml". I therefore want the project to build easily with newer Qt 5.11 and MSVC versions.

### CODE REVIEW

**Comment by forderud** [comment]
Gentle reminder.

**Comment by forderud** [comment]
@mattfife Any hope for getting this PR merged, or should I instead start on making my own fork?

**Review by mattropolis — APPROVED** [review]

**Comment by forderud** [comment]
You’ll also need to press the «merge» button, since I don’t have access to it.

**Review by mattropolis — APPROVED** [review]

**Review by mattropolis — APPROVED** [review]

**Review by mattropolis — APPROVED** [review]

**Comment by mattfife** [comment]
Sorry - have been traveling overseas for last few weeks. Everything should be merged. Let me know if you have any issues.

**Comment by forderud** [comment]
Thank’s a lot 😀

**Pull request merged**
